### ISSUE TITLE
Add Enigma logo to front page

### ISSUE THREAD

**Issue by maryjgoldman** [BD2KGenomics/brca-exchange#102]
Outstanding question: top or bottom? Draft it on the bottom and see what the group says.

**Comment by melissacline** [comment]
Background text:
Dear Melissa and Mary

here is one to file for when you have other suggestions for updates to the main "variants" expert-reviewed page -would it be possible to include the ENIGMA logo on the bottom together with BRCA exchange (or better still at the top somewhere). I think appropriate since this is the page that shows ENIGMA reviewed classification

tks
abs

**Comment by melissacline** [comment]
So, the upshot is to display the ENIGMA logo somewhere on the Variants page in the Expert Reviewed portal.  Use your judgment on where it would look best.

**Comment by maryjgoldman** [comment]
Duplicated by #264
