### ISSUE TITLE
autocomplete does not appear to work on the beta site

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca-exchange#194]
On brcaexchange.org, when you begin to enter the name of a variant in one of the search boxes (e.g. c.1105G>A), you're prompted with a list of matching variants.  This isn't working on the beta site.

**Comment by zfisch** [comment]
@melissacline The issue is that the migration that populates the WORDS DB table used for autocomplete (0004_autocomplete_words.py) is run before any data is in the DB in the versioning-1.0 branch. This is a result of migration changes in the versioning-1.0 branch and will be addressed as part of the migrations refactor.

**Comment by melissacline** [comment]
Great news!
