### ISSUE TITLE
Determine why the pipeline code cannot download BRCA2 data from LOVD

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca-exchange#262]
While the pipeline code is able to download new variant data for BRCA1, it has not been able to download new data for BRCA2, even though it's unclear why the same code would not work for both genes.

**Comment by falquaddoomi** [comment]
The error report from the pipeline code is misleading, since the message only mentions BRCA2.txt, but as far as I can tell from running extract_data.py with the same arguments from the pipeline neither BRCA1 nor BRCA2 are being downloaded.

After some investigation into the LOVD parsing library we're using, I found that the code never checks more than the first page (out of 23) when building the list of available genes. Furthermore, it fails to download the BRCA2 variants at all due to a column in one row having a value that parses to `None`, on which the code then attempts to invoke `.strip()`. The issues have been submitted to the source repo's issue tracker:

- **"_LOVD3Database doesn't acquire full list of genes":**
https://github.com/andrewhill157/leiden/issues/44
- **"_LOVD3GeneData occasionally fails when attempting to extract text from a field that begins with HTML":**
https://github.com/andrewhill157/leiden/issues/45

I'll be submitting PRs that fix each one later today, and we can use my fork of the project for the time being.

**Comment by falquaddoomi** [comment]
I've submitted the PRs to the original author's repo, waiting on a response. In the meantime, here's a link to the fork where I've merged both fixes into master: https://github.com/falquaddoomi/leiden

You can install this version from Github with the following terminal commands:

```bash
pip uninstall leiden # assuming it's previously installed
pip install -e git+https://github.com/falquaddoomi/leiden.git#egg=leiden
```

**Comment by zfisch** [comment]
Nice work! I'll try this out later today.
