### ISSUE TITLE
GA4GH API not returning all variants

### ISSUE THREAD

**Issue by david4096** [BD2KGenomics/brca-exchange#386]
As observed by @almussel the GA4GH API is serving some subset of the variants hosted by the BRCA exchange:
```
from ga4gh.client import client
c = client.HttpClient("http://brcaexchange.org/backend/data/ga4gh/v0.6.0a7") 
# This takes a few seconds
brca1 = len(list(c.search_variants(variant_set_id='brca-hg37', start=0, end=123123123123, reference_name="17")))
# 2242
brca2 = len(list(c.search_variants(variant_set_id='brca-hg37', start=0, end=123123123123, reference_name="13")))
# 2824
```
I suspect this might be due to how the data releases are being handled and that only differences are added to new releases. https://github.com/BD2KGenomics/brca-exchange/blob/master/website/django/data/views.py#L355

Is there something else that could be causing us to be getting so few variants? What is the correct way to get all of the variants for these variant sets? Once we've figured out a way to present only the latest, but not just the differences, we can evaluate added variant sets that go with different data releases.

Thanks!

**Comment by strbean** [comment]
Hey David! I was just looking at this after it was discussed in the BRCA Planning Group call. I agree with your conclusion.

We now have a materialized view with the most recent version of each variants. It is represented by the CurrentVariant model. Instead of accessing Variant.objects, use CurrentVariant.objects
