### ISSUE TITLE
Add new "Roles" to Community Pages signup

### ISSUE THREAD

**Issue by melissacline** [BD2KGenomics/brca-exchange#46]
1. Change Affiliation to Role
2. Add Patient / Proband to the top of the list

**Comment by maryjgoldman** [comment]
Change 'I lead a principal investigator' to 'I am a principal investigator'

**Comment by maryjgoldman** [comment]
Also, can we lowercase Clinical Lab Director so it's more consistent with the rest of the roles?

**Comment by maryjgoldman** [comment]
Melissa and I just talked and we agreed that we need to remove 'patient' and 'proband' from the list of roles due to concerns about these people becoming identifiable. Instead:
- remove patient/proband
-add at the top of the list 'I am an engaged member of the public'

This change may need to be discussed on the next EGG call on Thursday
